[package]
name = "blockchain_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.8.2"
chrono = "0.4.24"
bincode = "1.3.3"
sha256 = "1.1.3"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.160", features = ["derive"] }
log = "0.4.17"
